server:
  port: 8082 # Port for the microservice

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ # URL of the Eureka server
  instance:
    prefer-ip-address: true