# Spring properties
#spring:
#  application:
#    name: school-api-gateway


server:
  port: 8084 # Port for the microservice

spring:
  main:
    web-application-type: reactive
  application:
    name: school-gateway-service  # Give it a name
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  # Auto-detect services in Eureka
          lower-case-service-id: true  # Match service names correctly
      routes:
        - id: auth-service
          uri: lb://SCHOOL-AUTH-SERVICE
          predicates:
            - Path=/api/auth/**  # Route requests with /api/auth/* to AUTH service
          filters:
            - name: CircuitBreaker
              args:
                name: authServiceCircuitBreaker
                fallbackUri: forward:/fallback/auth

        - id: student-service
          uri: lb://SCHOOL-STUDENT-SERVICE
          predicates:
            - Path=/api/students/**  # Route requests with /api/students/* to Student service

          filters:
            - name: CircuitBreaker
              args:
                name: studentServiceCircuitBreaker
                fallbackUri: forward:/fallback/students

        - id: config-service
          uri: lb://SCHOOL-CONFIG-SERVICE
          predicates:
            - Path=/api/config/**  # Route requests with /api/config/* to Config service

          filters:
            - name: CircuitBreaker
              args:
                name: configServiceCircuitBreaker
                fallbackUri: forward:/fallback/config


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ # URL of the Eureka server
  instance:
    prefer-ip-address: true # Use IP address instead of hostname

management:
  endpoints:
    web:
      exposure:
        include: "gateway, health, info, metrics"
  endpoint:
    gateway:
      enabled: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
